# Generated by Django 2.2.5 on 2019-09-14 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_num', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('pass_hash', models.CharField(max_length=64)),
                ('salt', models.CharField(max_length=30)),
                ('balance', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_trade', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.CharField(max_length=12)),
                ('quantity', models.FloatField()),
                ('buy_or_sell', models.CharField(max_length=12)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_on_wallet.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=12)),
                ('quantity', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_on_wallet.Account')),
            ],
        ),
    ]
