# Generated by Django 2.2.5 on 2019-09-14 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_on_wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='pass_hash',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='account',
            name='salt',
        ),
    ]
