# Generated by Django 2.2.5 on 2019-09-16 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_on_wallet', '0003_account_salt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='password',
            new_name='pass_hash',
        ),
    ]
