# Generated by Django 2.2.5 on 2019-09-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_on_wallet', '0004_auto_20190916_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
    ]
